### ISSUE TITLE
Please update the 'StarlingX Project Overview' Deck on https://www.starlingx.io/learn/

### ISSUE THREAD

**Issue by gwaines** [StarlingXWeb/starlingx-website#39]
We have updated the 'StarlingX Project Overview' Deck to align with StarlingX 2.0 Release.  See the attached PDF for the updated deck.
This should replace:
https://www.starlingx.io/collateral/StarlingX-Onboarding-Deck-for-Web-February-2019.pdf

thanks
Greg.
[StarlingX Onboarding Deck for Web July 2019.pdf](https://github.com/StarlingXWeb/starlingx-website/files/3392060/StarlingX.Onboarding.Deck.for.Web.July.2019.pdf)

**Comment by ildikov** [comment]
Hi Greg,

Thank you for sending over the new version. It looks good after the first quick check.

There are a few small things to fix before uploading it to the website. I saw that you have the old OpenStack logo in the slides. And the camelcase for OpenStack is also incorrect on a few slides with using 'Openstack'.

I'm happy to fix these if you can send me over the source file. otherwise you can find the new logo here: https://www.openstack.org/brand/openstack-logo/logo-download/

Another question is that how much we want to have the overview up that introduces the 2.0 release architecture before it is actually available?

Thanks,
Ildikó

**Comment by ildikov** [comment]
A polished version from Glenn who's been using the slide deck extensively:
[StarlingX Onboarding Deck for 2.0 - glenn.pdf](https://github.com/StarlingXWeb/starlingx-website/files/3575467/StarlingX.Onboarding.Deck.for.2.0.-.glenn.pdf)

Ildiko's current version of an attempt to polish the slides based on the versions from Greg and Glenn:
[StarlingX Onboarding Deck for Web September 2019.pdf](https://github.com/StarlingXWeb/starlingx-website/files/3575473/StarlingX.Onboarding.Deck.for.Web.September.2019.pdf)

**Comment by ildikov** [comment]
Latest version of the slide deck: 
[StarlingX Onboarding Deck for Web September 2019_v3.pdf](https://github.com/StarlingXWeb/starlingx-website/files/3892062/StarlingX.Onboarding.Deck.for.Web.September.2019_v3.pdf)

**Comment by ildikov** [comment]
Latest overview diagram:

![StarlingX_Diagram_Distributed_Edge_Cloud_Native_3](https://user-images.githubusercontent.com/6662817/72329198-9c267280-36b4-11ea-9be8-d8d17a5d4f2b.jpg)

**Comment by yhu6** [comment]
I could suggest to make "IPMI" box to "IPMI Redfish". We now are supporting both.

**Comment by ildikov** [comment]
Overview slide deck with updated diagram:

[StarlingX Onboarding Deck for Web September 2019.pdf](https://github.com/StarlingXWeb/starlingx-website/files/4085646/StarlingX.Onboarding.Deck.for.Web.September.2019.pdf)

**Comment by ildikov** [comment]
Fixed the above comment in the overview diagram and added slides back about Distributed Cloud:

[StarlingX Onboarding Deck for Web January 2020.pdf](https://github.com/StarlingXWeb/starlingx-website/files/4097815/StarlingX.Onboarding.Deck.for.Web.January.2020.pdf)

**Comment by ildikov** [comment]
This issue is now resolved, the diagram and the slide deck is updated on the starlingx.io website.
